version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    volumes:
      - static_files:/src/static
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx:/etc/nginx/templates
      - static_files:/var/www/static
    ports:
      - 8000:9999
    environment:
      - APP_HOST=web
      - APP_PORT=8000
      - PORT=9999
    depends_on:
      - web
    restart: always

volumes:
  static_files:
