version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/renalreg/mauritius-renaldataregistry:main
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
