# Generated by Django 3.2.6 on 2022-05-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models

# pylint: disable=too-many-lines


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comorbidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comorbidity", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="co_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="co_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disability", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dis_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dis_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HDUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hdu_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hdu_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Unknown"), (1, "Public"), (2, "Private")],
                        default=0,
                        verbose_name="Institution type",
                    ),
                ),
                (
                    "is_unit_required",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hi_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hi_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        verbose_name="N.I.C no. (or passport no. for foreigners)",
                    ),
                ),
                (
                    "id_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "N.I.C"), (2, "Passport")],
                        default=1,
                        verbose_name="Unique identifier type",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Other Name/s")),
                ("surname", models.CharField(max_length=100, verbose_name="Surname")),
                ("dob", models.DateField(verbose_name="Date of birth")),
                (
                    "ethnic",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "General population"),
                            (2, "Hindu"),
                            (3, "Islam"),
                            (4, "Chinese (Buddhist)"),
                            (5, "Other"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="Ethnic group",
                    ),
                ),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                        default=1,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "maritalstatus",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Single"),
                            (2, "Married (Concub...)"),
                            (3, "Widow"),
                            (4, "Divorced (Sep)"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="Marital status",
                    ),
                ),
                (
                    "occupationalstatus",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Employed"),
                            (2, "Housewife"),
                            (3, "Unemployed"),
                            (4, "Retired"),
                        ],
                        default=1,
                        null=True,
                        verbose_name="Occupation",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Height (cm)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "birth_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Birth weight (kg)",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Postcode"
                    ),
                ),
                (
                    "current_occupation",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Current employment",
                    ),
                ),
                (
                    "prev_occupation1",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Significant previous occupation 1",
                    ),
                ),
                (
                    "prev_occupation2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Significant previous occupation 2",
                    ),
                ),
                (
                    "prev_occupation3",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Significant previous occupation 3",
                    ),
                ),
                (
                    "prev_occupation4",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Significant previous occupation 4",
                    ),
                ),
                (
                    "in_krt_modality",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="Is patient on Kidney Replacement Therapy (KRT)?",
                    ),
                ),
                (
                    "landline_number",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="Home phone number",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Mobile phone number",
                    ),
                ),
                (
                    "alternative_numbers",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Alternative numbers",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "email2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Alternative email",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pat_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pat_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smokingstatus",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Never smoked"),
                            (2, "Smoker"),
                            (3, "Stopped"),
                        ],
                        default=0,
                        verbose_name="Smoking status",
                    ),
                ),
                (
                    "alcoholuse",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Never"),
                            (2, "Active"),
                            (3, "Stopped"),
                        ],
                        default=0,
                        verbose_name="Alcohol use disorder",
                    ),
                ),
                (
                    "hepatitis_b",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Positive"),
                            (2, "Negative"),
                            (3, "Immune"),
                        ],
                        default=0,
                        verbose_name="Hepatitis B",
                    ),
                ),
                (
                    "hepatitis_c",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Positive"),
                            (2, "Negative"),
                            (3, "Cured"),
                        ],
                        default=0,
                        verbose_name="Hepatitis C",
                    ),
                ),
                (
                    "hiv",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Unknown"), (1, "Positive"), (2, "Negative")],
                        default=0,
                        verbose_name="HIV",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comorbidity",
                    models.ManyToManyField(
                        blank=True,
                        to="renaldataregistry.Comorbidity",
                        verbose_name="Comorbidities",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pas_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disability",
                    models.ManyToManyField(
                        blank=True,
                        to="renaldataregistry.Disability",
                        verbose_name="Disabilities",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="renaldataregistry.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pas_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientDialysisAssessment",
            fields=[
                (
                    "patientassessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="renaldataregistry.patientassessment",
                    ),
                ),
                (
                    "posthd_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Post HD or dry PD weight in kg",
                    ),
                ),
                (
                    "hd_sessions",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Sessions/week"
                    ),
                ),
                (
                    "hd_minssessions",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Mins/session"
                    ),
                ),
                (
                    "hd_adequacy_urr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="URR %",
                    ),
                ),
                (
                    "hd_adequacy_kt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Kt/v",
                    ),
                ),
                (
                    "pd_exchangesday",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Exchanges/day"
                    ),
                ),
                (
                    "pd_fluidlitresday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Fluid litres/day",
                    ),
                ),
                (
                    "pd_adequacy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Kt/V urea",
                    ),
                ),
                (
                    "pd_bp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="BP in mmHg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientLPAssessment",
            fields=[
                (
                    "patientassessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="renaldataregistry.patientassessment",
                    ),
                ),
                (
                    "hb_gdl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Hb g/dl",
                    ),
                ),
                (
                    "calcium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Calcium mmol/l",
                    ),
                ),
                (
                    "ferritin",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ferritin ng/ml*"
                    ),
                ),
                (
                    "albumin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Albumin g/l",
                    ),
                ),
                (
                    "phosphate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Phosphate mmol/l",
                    ),
                ),
                (
                    "tsat",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="TSAT %*"
                    ),
                ),
                (
                    "bicarbonate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Bicarbonate mmol/l",
                    ),
                ),
                (
                    "hba1c",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="HbA1C %*"
                    ),
                ),
                (
                    "pth",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="PTH pmol/l*"
                    ),
                ),
            ],
            options={
                "db_table": "renaldataregistry_patientassessment_lp",
            },
        ),
        migrations.CreateModel(
            name="PatientMedicationAssessment",
            fields=[
                (
                    "patientassessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="renaldataregistry.patientassessment",
                    ),
                ),
                (
                    "iu_wk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="iu/wk (short acting)",
                    ),
                ),
                (
                    "mcg2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="mcg/2 wk (darbo.)",
                    ),
                ),
                (
                    "mcg4",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="mcg/4 wk (mircera)",
                    ),
                ),
                (
                    "mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="mg/month",
                    ),
                ),
                (
                    "insulin",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="Insulin",
                    ),
                ),
                (
                    "sulphonylureas",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="Sulphonylureas",
                    ),
                ),
                (
                    "antidiab_others1",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="1"
                    ),
                ),
                (
                    "antidiab_others2",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="2"
                    ),
                ),
                (
                    "antidiab_others3",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="3"
                    ),
                ),
                (
                    "acei",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="ACEi",
                    ),
                ),
                (
                    "arb",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="ARB",
                    ),
                ),
                (
                    "cc_blocker",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="CC Blocker",
                    ),
                ),
                (
                    "beta_blocker",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="Beta Blocker",
                    ),
                ),
                (
                    "alpha_blocker",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="Alpha Blocker",
                    ),
                ),
                (
                    "methyldopa",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        max_length=1,
                        verbose_name="Methyldopa",
                    ),
                ),
                (
                    "antihypertensives_others1",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="1"
                    ),
                ),
                (
                    "antihypertensives_others2",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="2"
                    ),
                ),
                (
                    "antihypertensives_others3",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="3"
                    ),
                ),
                (
                    "antihypertensives_others4",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="4"
                    ),
                ),
                (
                    "antihypertensives_others5",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="5"
                    ),
                ),
            ],
            options={
                "db_table": "renaldataregistry_patientassessment_med",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="u_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "healthinstitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="renaldataregistry.healthinstitution",
                        verbose_name="Health institution",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="u_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenalDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rd_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rd_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientRenalDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "is_primary_renaldiagnosis",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="renaldataregistry.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "renaldiagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="renaldataregistry.renaldiagnosis",
                        verbose_name="ERA-EDTA CODE",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientKRTModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "NK"), (2, "HD"), (3, "PD"), (4, "TX")],
                        default=1,
                        verbose_name="KRT modality",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date started"
                    ),
                ),
                (
                    "hd_initialaccess",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "AVF"),
                            (2, "AVG"),
                            (3, "TC"),
                            (4, "NTC"),
                        ],
                        default=0,
                        verbose_name="Access on first HD",
                    ),
                ),
                (
                    "hd_ntcreason",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Unknown"),
                            (1, "AVF/G not ready"),
                            (2, "AVF/G dysfunction"),
                            (3, "On waiting list"),
                            (4, "No veins"),
                            (5, "Patient choice"),
                        ],
                        default=0,
                        verbose_name="If on NTC, why?",
                    ),
                ),
                (
                    "before_KRT",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("U", "Unknown"),
                            ("ROPD", "ROPD"),
                            ("MOPD", "MOPD"),
                            ("LHC", "LHC"),
                            ("OTHER_DR", "Other hospital Dr"),
                            ("PRIV_NEPHR", "Private Nephrologist"),
                            ("OTHER_PRIV_DR", "Other private Dr"),
                        ],
                        default="U",
                        max_length=13,
                        verbose_name="Which of the following has the patient seen in the year before starting KRT?",
                    ),
                ),
                (
                    "ropdorprivnephr_days",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Time first seen by ROPD or private nephrologist in days before start of KRT",
                    ),
                ),
                (
                    "hepB_vac",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                        verbose_name="Has the patient completed Hep B vaccination?",
                    ),
                ),
                (
                    "delay_start",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                        verbose_name="Did patient delay the start of dialysis despite nephrology advice?",
                    ),
                ),
                (
                    "delay_beforedialysis",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Delay in full days in start of dialysis",
                    ),
                ),
                (
                    "hd_unusedavfavgreason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("U", "Unknown"),
                            ("NC", "Not created"),
                            ("NR", "Not ready"),
                            ("AF", "Already failed"),
                        ],
                        default="U",
                        max_length=2,
                        verbose_name="Why AVF/AVG not used to initiate HD?",
                    ),
                ),
                (
                    "pd_catheterdays",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="How early was the PD catheter inserted (whole days before first exchange)?",
                    ),
                ),
                (
                    "pd_insertiontechnique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("U", "Unknown"),
                            ("OS", "Open surgery"),
                            ("L", "Laparoscopic"),
                            ("P", "Percutaneous"),
                        ],
                        default="U",
                        max_length=2,
                        verbose_name="PD insertion technique",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pkrt_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hd_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="renaldataregistry.hdunit",
                        verbose_name="If HD, state unit",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="renaldataregistry.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pkrt_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPatientRegistration",
            fields=[
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_institution",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="renaldataregistry.healthinstitution",
                        verbose_name="Health institution",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="renaldataregistry.patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical patient registration",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PatientStop",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="renaldataregistry.patient",
                    ),
                ),
                (
                    "last_dialysis_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of last dialysis"
                    ),
                ),
                (
                    "stop_reason",
                    models.CharField(
                        choices=[
                            ("D", "Died"),
                            ("RKF", "Recovered kidney function"),
                            ("DR", "Doctor’s recommendation"),
                            ("LF", "Lost to follow-up"),
                            ("LM", "Left Mauritius"),
                            ("FC", "Patient or family choice"),
                        ],
                        default="D",
                        max_length=3,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "dod",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of death"
                    ),
                ),
                (
                    "cause_of_death",
                    models.CharField(
                        choices=[
                            ("U", "Unknown"),
                            ("C", "Cardiovascular"),
                            ("CV", "Cerebrovascular"),
                            ("I", "Infection"),
                            ("M", "Malignancy"),
                            ("SD", "Stopped dialysis"),
                        ],
                        default="D",
                        max_length=2,
                        verbose_name="Cause of death",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dod_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dod_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "renaldataregistry_patientendoftreatment",
            },
        ),
        migrations.CreateModel(
            name="PatientRegistration",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="renaldataregistry.patient",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reg_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="renaldataregistry.healthinstitution",
                        verbose_name="Health institution",
                    ),
                ),
                (
                    "unit",
                    models.ManyToManyField(
                        blank=True,
                        to="renaldataregistry.Unit",
                        verbose_name="Unit number/s",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reg_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientAKImeasurement",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="renaldataregistry.patient",
                    ),
                ),
                (
                    "creatinine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Latest creatinine (μmol/l)",
                    ),
                ),
                (
                    "egfr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Latest eGFR (ml/min)",
                    ),
                ),
                (
                    "hb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Latest Hb",
                    ),
                ),
                (
                    "measurement_date",
                    models.DateField(blank=True, null=True, verbose_name="Date done"),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paki_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paki_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
