# Generated by Django 3.2.6 on 2022-06-06 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientrenaldiagnosis",
            name="renaldiagnosis",
        ),
        migrations.AddField(
            model_name="patientrenaldiagnosis",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                validators=[django.core.validators.RegexValidator("^\\d{1,10}$")],
                verbose_name="ERA-EDTA CODE",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="hd_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="renaldataregistry.hdunit",
                verbose_name="If HD, state HD unit",
            ),
        ),
        migrations.DeleteModel(
            name="RenalDiagnosis",
        ),
    ]
