# Generated by Django 3.2.6 on 2021-09-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renaldataregistry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientassessment',
            name='laboratoryparameter',
        ),
    ]
