# Generated by Django 3.2.6 on 2021-09-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0002_remove_patientassessment_laboratoryparameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientassessment",
            name="medication",
        ),
    ]
