# Generated by Django 3.2.6 on 2022-06-06 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0002_alter_renaldiagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientassessment",
            name="clinical_frailty",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
                verbose_name="Clinical frailty scale (1 to 9)",
            ),
        ),
    ]
