# Generated by Django 3.2.6 on 2022-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0002_alter_patient_pid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmeasurement",
            name="measurementtype",
            field=models.PositiveSmallIntegerField(verbose_name="Measurement type"),
        ),
    ]
