# Generated by Django 3.2.6 on 2022-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0003_patientassessment_clinical_frailty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientmedicationassessment",
            name="antidiab_others1",
        ),
        migrations.RemoveField(
            model_name="patientmedicationassessment",
            name="antidiab_others2",
        ),
        migrations.RemoveField(
            model_name="patientmedicationassessment",
            name="antidiab_others3",
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="acarbose",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Acarbose",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antidiabetic_other",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Other",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="dpp4i",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="DPP4i",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="glp1a",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="GLP1A",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="meglitinides",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Meglitinides",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="metformin",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Metformin",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="sglt2i",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="SGLT2i",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="acei",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="ACEi",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="alpha_blocker",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Alpha Blocker",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="arb",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="ARB",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="beta_blocker",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Beta Blocker",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="cc_blocker",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="CC Blocker",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="insulin",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Insulin",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="methyldopa",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Methyldopa",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="sulphonylureas",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Sulphonylureas",
            ),
        ),
    ]
