# Generated by Django 3.2.6 on 2021-11-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0004_medication_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientregistration",
            name="id",
        ),
        migrations.AlterField(
            model_name="patientregistration",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="renaldataregistry.patient",
            ),
        ),
    ]
