# Generated by Django 3.2.6 on 2022-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0005_patientassessmentmed_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientkrtmodality",
            name="hd_privatestart",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Was HD started in private?",
            ),
        ),
    ]
