# Generated by Django 3.2.6 on 2022-04-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0006_historicalpatientregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientcontact",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patientcontact",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patientcontact",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="patientmeasurement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patientmeasurement",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patientmeasurement",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="patientoccupation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patientoccupation",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patientoccupation",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="historicalpatientregistration",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="patientakimeasurement",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="patientakimeasurement",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patientakimeasurement",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="patientakimeasurement",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="patientrenaldiagnosis",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="patientrenaldiagnosis",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patientrenaldiagnosis",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="patientrenaldiagnosis",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="healthinstitution",
            name="is_unit_required",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Birth weight (kg)",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_occupation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Current employment"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="email2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Alternative email"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Height (cm)",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="in_krt_modality",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Is patient on Kidney Replacement Therapy (KRT)?",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="landline_number1",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="Home phone number"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="landline_number2",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                verbose_name="Alternative landline number",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mobile_number1",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Mobile phone number"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mobile_number2",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                verbose_name="Alternative mobile number",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="postcode",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Postcode"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prev_occupation1",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Significant previous occupation 1",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prev_occupation2",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Significant previous occupation 2",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prev_occupation3",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Significant previous occupation 3",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="prev_occupation4",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Significant previous occupation 4",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="street",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Weight (kg)",
            ),
        ),
        migrations.AddField(
            model_name="patientrenaldiagnosis",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Primary renal diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="before_KRT",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Unknown"),
                    ("ROPD", "ROPD"),
                    ("MOPD", "MOPD"),
                    ("LHC", "LHC"),
                    ("OTHER_DR", "Other hospital Dr"),
                    ("PRIV_NEPHR", "Private Nephrologist"),
                    ("OTHER_PRIV_DR", "Other private Dr"),
                ],
                default="U",
                max_length=13,
                verbose_name="Which of the following has the patient seen in the year before starting KRT?",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="delay_start",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Did patient delay the start of dialysis despite nephrology advice?",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="hd_initialaccess",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Unknown"), (1, "AVF"), (2, "AVG"), (3, "TC"), (4, "NTC")],
                default=0,
                verbose_name="If HD was the first KRT, what was the initial access?",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="hd_ntcreason",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Unknown"),
                    (1, "AVF/G not ready"),
                    (2, "AVF/G dysfunction"),
                    (3, "On waiting list"),
                    (4, "No veins"),
                    (5, "Patient choice"),
                ],
                default=0,
                verbose_name="If on NTC, why?",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="hd_unusedavfavgreason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Unknown"),
                    ("NC", "Not created"),
                    ("NR", "Not ready"),
                    ("AF", "Already failed"),
                ],
                default="U",
                max_length=2,
                verbose_name="Why AVF/AVG not used to initiate HD?",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="hepB_vac",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                default="U",
                max_length=1,
                verbose_name="Has the patient completed Hep B vaccination?",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="is_current",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="pd_insertiontechnique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Unknown"),
                    ("OS", "Open surgery"),
                    ("L", "Laparoscopic"),
                    ("P", "Percutaneous"),
                ],
                default="U",
                max_length=2,
                verbose_name="PD insertion technique:",
            ),
        ),
        migrations.AlterField(
            model_name="patientregistration",
            name="health_institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="renaldataregistry.healthinstitution",
                verbose_name="Health institution",
            ),
        ),
        migrations.RemoveField(
            model_name="patientregistration",
            name="unit",
        ),
        migrations.AddField(
            model_name="patientregistration",
            name="unit",
            field=models.ManyToManyField(
                blank=True, to="renaldataregistry.Unit", verbose_name="Unit"
            ),
        ),
        migrations.AlterField(
            model_name="patientrenaldiagnosis",
            name="renaldiagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="renaldataregistry.renaldiagnosis",
                verbose_name="ERA-EDTA CODE",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="healthinstitution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="renaldataregistry.healthinstitution",
                verbose_name="Health institution",
            ),
        ),
        migrations.DeleteModel(
            name="PatientAddress",
        ),
        migrations.DeleteModel(
            name="PatientContact",
        ),
        migrations.DeleteModel(
            name="PatientMeasurement",
        ),
        migrations.DeleteModel(
            name="PatientOccupation",
        ),
    ]
