# Generated by Django 3.2.6 on 2022-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0007_alter_patientregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthinstitution",
            name="is_unit_required",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Other Name/s"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="occupationalstatus",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Employed"),
                    (2, "Housewife"),
                    (3, "Unemployed"),
                    (4, "Retired"),
                ],
                default=1,
                null=True,
                verbose_name="Occupation",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="pid",
            field=models.CharField(
                max_length=14,
                unique=True,
                verbose_name="N.I.C no. (or passport no. for foreigners)",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="surname",
            field=models.CharField(max_length=100, verbose_name="Surname"),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="is_current",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
