# Generated by Django 3.2.6 on 2022-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0007_alter_patientkrtmodality_hd_privatestart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientkrtmodality",
            name="hd_ntcreason",
        ),
        migrations.AddField(
            model_name="patientkrtmodality",
            name="hd_tc_ntc_reason",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Unknown"),
                    (1, "AVF/G not ready"),
                    (2, "AVF/G dysfunction"),
                    (3, "On waiting list"),
                    (4, "No veins"),
                    (5, "Patient choice"),
                ],
                default=0,
                verbose_name="If on TC or NTC, why?",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="hd_initialaccess",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Unknown"), (1, "AVF"), (2, "AVG"), (3, "TC"), (4, "NTC")],
                default=0,
            ),
        ),
    ]
