# Generated by Django 3.2.6 on 2022-04-26 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("renaldataregistry", "0008_alter_forkrt"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientakimeasurement",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientakimeasurement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paki_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientakimeasurement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientakimeasurement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paki_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientkrtmodality",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientkrtmodality",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pkrt_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patientkrtmodality",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patientkrtmodality",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pkrt_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpatientregistration",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="patientassessment",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="hd_initialaccess",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Unknown"), (1, "AVF"), (2, "AVG"), (3, "TC"), (4, "NTC")],
                default=0,
                verbose_name="Access on first HD",
            ),
        ),
        migrations.AlterField(
            model_name="patientkrtmodality",
            name="modality",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "NK"), (2, "HD"), (3, "PD"), (4, "TX")],
                default=1,
                verbose_name="KRT modality",
            ),
        ),
        migrations.AlterField(
            model_name="patientregistration",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
