# Generated by Django 3.2.6 on 2022-05-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("renaldataregistry", "0009_alter_krtmod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="patientlpassessment",
            name="assessment_value",
        ),
        migrations.RemoveField(
            model_name="patientlpassessment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="patientlpassessment",
            name="laboratoryparameter",
        ),
        migrations.RemoveField(
            model_name="patientmedicationassessment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="patientmedicationassessment",
            name="medication",
        ),
        migrations.RemoveField(
            model_name="patientmedicationassessment",
            name="medication_value",
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="albumin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Albumin g/l",
            ),
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="bicarbonate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Bicarbonate mmol/l",
            ),
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="calcium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Calcium mmol/l",
            ),
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="ferritin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Ferritin ng/ml",
            ),
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="hb_gdl",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Hb g/dl",
            ),
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="hba1c",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="HbA1C %*"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="phosphate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Phosphate mmol/l",
            ),
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="pth",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="PTH pmol/l*"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientlpassessment",
            name="tsat",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="TSAT %*"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="acei",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="ACEi",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="alpha_blocker",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Alpha Blocker",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antidiab_others1",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="1"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antidiab_others2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="2"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antidiab_others3",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="3"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antihypertensives_others1",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="1"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antihypertensives_others2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="2"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antihypertensives_others3",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="3"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antihypertensives_others4",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="4"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="antihypertensives_others5",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="5"
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="arb",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="ARB",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="beta_blocker",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Beta Blocker",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="cc_blocker",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="CC Blocker",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="insulin",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Insulin",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="iu_wk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="iu/wk (short acting)",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="mcg2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="mcg/2 wk (darbo.)",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="mcg4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="mcg/4 wk (mircera)",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="methyldopa",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Methyldopa",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="mg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="mg/month",
            ),
        ),
        migrations.AddField(
            model_name="patientmedicationassessment",
            name="sulphonylureas",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="N",
                max_length=1,
                verbose_name="Sulphonylureas",
            ),
        ),
        migrations.AlterField(
            model_name="patientlpassessment",
            name="patientassessment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="renaldataregistry.patientassessment",
            ),
        ),
        migrations.AlterField(
            model_name="patientmedicationassessment",
            name="patientassessment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="renaldataregistry.patientassessment",
            ),
        ),
        migrations.AlterField(
            model_name="patientstop",
            name="dod",
            field=models.DateField(blank=True, null=True, verbose_name="Date of death"),
        ),
        migrations.AlterField(
            model_name="patientstop",
            name="last_dialysis_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date of last dialysis"
            ),
        ),
        migrations.AlterField(
            model_name="patientstop",
            name="stop_reason",
            field=models.CharField(
                choices=[
                    ("D", "Died"),
                    ("RKF", "Recovered kidney function"),
                    ("DR", "Doctor’s recommendation"),
                    ("LF", "Lost to follow-up"),
                    ("LM", "Left Mauritius"),
                    ("FC", "Patient or family choice"),
                ],
                default="D",
                max_length=3,
                verbose_name="Reason",
            ),
        ),
        migrations.DeleteModel(
            name="LaboratoryParameter",
        ),
        migrations.DeleteModel(
            name="Medication",
        ),
    ]
