# Generated by Django 3.2.6 on 2021-08-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInstitution',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('A', 'Public'), ('P', 'Private'), ('', 'Select...')], default='', max_length=2, verbose_name='Institution type')),
            ],
        ),
    ]
